- name: "bug"
  color: "d73a4a"
  description: "Something isn't working"
- name: "documentation"
  color: "0075ca"
  description: "Improvements or additions to documentation"
- name: "duplicate"
  color: "cfd3d7"
  description: "This issue or pull request already exists"
- name: "enhancement"
  color: "a2eeef"
  description: "New feature or request"
- name: "chore"
  color: "CD026F"
  description: "Changes to how we maintain the repository"
- name: "good first issue"
  color: "7057ff"
  description: "Good for newcomers"
- name: "help wanted"
  color: "008672"
  description: "This issue is ready for contributing a PR"
- name: "question"
  color: "d876e3"
  description: "Further information is requested"
- name: "wontfix"
  color: "ffffff"
  description: "This will not be worked on"
- name: "stale"
  color: "4252e5"
  description: "Stale issues and PRs will be closed automatically"
- name: "hacktoberfest"
  color: "FF8AE2"
  description: "Issues prepared for Hacktoberfest"
- name: "invalid"
  color: "FCBA03"
  description: "PRs marked as invalid so they don't count for Hacktoberfest"
