pull_request_rules:
  - name: merge reviewed and built PRs
    conditions:
      - base=main
      - "#approved-reviews-by>=1"
      - status-success=build (2.x)
      - status-success=build (3.x)
      - status-success=build (4.x)
      - status-success=license/cla
    actions:
      merge:
        method: merge

  - name: merge reviewed PRs from the repo owner
    conditions:
      - author=dbartholomae
      - base=main
      - status-success=build (2.x)
      - status-success=build (3.x)
      - status-success=build (4.x)
    actions:
      merge:
        method: merge

  - name: automatic merge for Dependabot pull requests
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - status-success=build (2.x)
      - status-success=build (3.x)
      - status-success=build (4.x)
    actions:
      merge:
        method: merge
