sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
before_install:
  - npm i -g npm@^5.0.0
before_script:
  - npm prune
after_success:
  - npm run coveralls
deploy:
  provider: script
  skip_cleanup: true
  script:
    - npx semantic-release
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
