# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  install:
    docker:
      - image: circleci/node:8
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install packages
          command: |
            yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - persist_to_workspace:
          root: .
          paths:
            - .

  build:
    docker:
      - image: circleci/node:8
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Build package
          command: |
            yarn run build
      - run:
          name: Build documentation
          command: |
            yarn run docs
      - persist_to_workspace:
          root: .
          paths:
          - .

  test:
    docker:
      - image: circleci/node:8
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run Linting
          command: |
            yarn lint
      - run:
          name: Run unit tests
          command: |
            yarn test --ci --testResultsProcessor="jest-junit"
          environment:
            JEST_JUNIT_OUTPUT: "reports/junit/js-unit-test-results.xml"
      - run:
          name: Run integration tests
          command: |
            concurrently --kill-others --success first "cd test && serverless offline" "wait-on http://localhost:3000/status && jest -c jest.integration.config.js --testResultsProcessor=\"jest-junit\""
          environment:
            JEST_JUNIT_OUTPUT: "reports/junit/js-integration-test-results.xml"
      - store_test_results:
          path: reports/junit

  release:
    docker:
    - image: circleci/node:8
    working_directory: ~/repo
    steps:
    - attach_workspace:
        at: .
    - run:
        name: Publish via semantic release
        command: |
          yarn run release

workflows:
  version: 2
  build-deploy:
    jobs:
      - install
      - build:
          requires:
            - install
      - test:
          requires:
            - build
      - release:
          requires:
          - build
          filters:
            branches:
              only:
              - master
